### ISSUE TITLE
Add text and morse code to dictionary 

### ISSUE THREAD

**Issue by VitaminMe** [VitaminMe/pyMorse#1]
The dictionary is used to look up the letter and return the corresponding value. To do this the 26 letters of the English alphabet and their [international morse](https://en.wikipedia.org/wiki/Morse_code#International_Morse_Code) equivalent must be added to the dictionary.

**Comment by lwdunnill** [comment]
#2 Has A to Z encoding (as well as numbers).  Additional functionality also added and QA too.

**Comment by VitaminMe** [comment]
Thanks. Closing this as it has been merged, forked, improved upon, and aged to a perfection over two years.
